theme: jekyll-theme-minimal
title: Ruoqing's Blog
SEOTitle: RQ BLOG
header-img: 
email: milkypashum@gmail.com
description: "RQ Blog"
keyword: "RQ, Ruoqing, UX, IxD"
url:"http://carroooot.github.io"

sidebar: true
sidebar-about-description:"what am I thinking when talking about UX Design"
sidebar-avatar:

RSS: false
